#ifndef SPECIAL_CHAR_H
#define SPECIAL_CHAR_H

#include <stdio.h>

/* XPM */
static xpm_row_t const points[] = {
/* columns rows colors chars-per-pixel */
"20 35 15 1 ",
"  c #000000",
". c #080808",
"X c #0D0D0D",
"o c #131313",
"O c #161616",
"+ c #2F2F2F",
"@ c #3F3F3F",
"# c #444444",
"$ c #525252",
"% c #555555",
"& c #929292",
"* c #CBCBCB",
"= c #E6E6E6",
"- c #ECECEC",
"; c #FFFFFF",
/* pixels */
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"        .*-#        ",
"        +;;&        ",
"        X=;$        ",
"         .o         ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"         .O         ",
"        X=;%        ",
"        +;;&        ",
"        .*-@        ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    "
};


/* XPM */
static xpm_row_t const bar[] = {
/* columns rows colors chars-per-pixel */
"20 35 26 1 ",
"  c #000000",
". c #050505",
"X c #0B0B0B",
"o c #161616",
"O c #171717",
"+ c #212121",
"@ c #323232",
"# c #343434",
"$ c #3F3F3F",
"% c #515151",
"& c #5F5F5F",
"* c #727272",
"= c #808080",
"- c #919191",
"; c #949494",
": c #9F9F9F",
"> c #B1B1B1",
", c #BFBFBF",
"< c #D1D1D1",
"1 c #D3D3D3",
"2 c #DEDEDE",
"3 c #EBEBEB",
"4 c #ECECEC",
"5 c #F3F3F3",
"6 c #FAFAFA",
"7 c #FFFFFF",
/* pixels */
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"           -7&      ",
"          .35X      ",
"          %7:       ",
"          >7$       ",
"         o62        ",
"         *7=        ",
"         <7+        ",
"        @7,         ",
"        -7&         ",
"       .45X         ",
"       %7:          ",
"       >7%          ",
"      O72           ",
"      *7=           ",
"      <7+           ",
"     #7,            ",
"     ;7&            ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    "
};


/* XPM */
static xpm_row_t const point[] = {
/* columns rows colors chars-per-pixel */
"20 35 12 1 ",
"  c #000000",
". c #080808",
"X c #0D0D0D",
"o c #161616",
"O c #2F2F2F",
"+ c #3F3F3F",
"@ c #555555",
"# c #929292",
"$ c #CACACA",
"% c #E6E6E6",
"& c #ECECEC",
"* c #FFFFFF",
/* pixels */
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"         .o         ",
"        X%*@        ",
"        O**#        ",
"        .$&+        ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    "
};


/* XPM */
static xpm_row_t const sub[] = {
/* columns rows colors chars-per-pixel */
"20 35 6 1 ",
"  c #000000",
". c #040404",
"X c #8F8F8F",
"o c #BCBCBC",
"O c #C4C4C4",
"+ c #FFFFFF",
/* pixels */
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"       OOOOOX       ",
"      .+++++o       ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    "
};

#endif // SPECIAL_CHAR_H
